= GraphQL Field-based Permissions Policy

== Phase

[cols="4*^",options="header"]
|===
|onRequest|onResponse|onMessageRequest|onMessageResponse

^.^|-
^.^|X
^.^|-
^.^|X

|===

== Description

You can use the `graphql-field-based-permissions` policy to block, mask, or exclude specific fields in the original response content from being returned to the consumer.
Works with any type of JSON payload.  (Support for XML payloads coming soon...)

Kafka Messages (for both Protocol Mediation and Native Kafka) - If you have chosen to block the message, then the gateway will only acknowledge the message. The acknowledgment will inform the message source that it has been successfully processed.

== Compatibility with APIM

|===
|Plugin version | APIM version

| 0.0.2         | 4.9.x to latest

|===

== Configuration

|===
|Property |Required |Description |Type |Default

.^|allowList
^.^|X
|(Coming soon...) A list of fields to allow from the returned payload - works like a white list.
^.^|list
^.^|-

.^|blockList
^.^|X
|A list of fields to block or exclude from the returned payload - overrides the allow list.
^.^|list
^.^|-

.^|responsePolicy
^.^|X
|Specify either BLOCK_RESPONSE, MASK_FIELDS, or REMOVE_BLOCKED_FIELDS
^.^|string
^.^|BLOCK_RESPONSE

|===

[source, json]
.Sample
----
"graphql-field-based-permissions": {
    "blockList": ["field1", "field2"],
    "responsePolicy": "BLOCK_RESPONSE"
}
----

== Errors

=== HTTP status code

|===
|Code |Message

.^| ```500```
| The body content cannot be transformed.

|===
